In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,9])
vector

tensor([7, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[7,9],
                     [9,8]])
matrix

tensor([[7, 9],
        [9, 8]])

In [ ]:
MATRIX=torch.tensor([[6,7],
                     [8,9]])
MATRIX

tensor([[6, 7],
        [8, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([8, 9])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR=torch.tensor([[[1,2],
                      [3,4],
                      [5,6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0236, 0.9562, 0.3998, 0.1218],
        [0.8132, 0.4009, 0.2687, 0.7373],
        [0.9784, 0.1721, 0.7814, 0.5756]])

In [ ]:
'''#Exercise 2
random_tensor=torch.rand(7,7)
random_tensor'''

tensor([[5.2761e-01, 2.9794e-01, 2.5828e-01, 9.8669e-01, 3.3409e-01, 4.8173e-01,
         7.8185e-01],
        [5.1314e-01, 7.5339e-01, 3.4194e-01, 5.6023e-01, 9.6697e-04, 1.4904e-01,
         6.8528e-01],
        [9.4969e-01, 7.9781e-01, 1.4376e-01, 5.5397e-01, 2.1608e-01, 1.2850e-01,
         3.0678e-01],
        [8.4878e-01, 5.9316e-01, 6.5335e-01, 5.5953e-01, 7.6165e-01, 1.2271e-01,
         3.7011e-01],
        [4.4383e-01, 9.8057e-01, 1.8687e-01, 9.9755e-01, 6.7783e-01, 8.2556e-01,
         9.7721e-01],
        [6.8657e-01, 8.4636e-03, 2.4779e-01, 7.4857e-01, 2.7425e-01, 7.1500e-01,
         3.2905e-01],
        [6.8247e-01, 5.4449e-01, 8.2626e-01, 5.0828e-01, 8.0131e-02, 8.6198e-01,
         7.2505e-02]])

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.shape

torch.Size([3, 4])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.range(0, 10)

<ipython-input-24-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Shape of tensor :{some_tensor.shape}")
print(f"Datatype of tensor :{some_tensor.dtype}")
print(f"Device tensor is stored on:{some_tensor.device}")

tensor([[0.3365, 0.2116, 0.7974, 0.4036],
        [0.1061, 0.5590, 0.5591, 0.2772],
        [0.3373, 0.6164, 0.9255, 0.5077]])
Shape of tensor :torch.Size([3, 4])
Datatype of tensor :torch.float32
Device tensor is stored on:cpu


In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor=tensor+10
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
print(tensor,"*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
import torch
tensor =torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
  value

CPU times: user 1.6 ms, sys: 0 ns, total: 1.6 ms
Wall time: 2.86 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 1.02 ms


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]],dtype=torch.float32)
tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]],dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
'''#Exercise 3
random_tensor_A=torch.rand(1,7)
print(random_tensor_A)
random_tensor_B=torch.rand(1,7)
print(random_tensor_B.T)

output=torch.matmul(random_tensor_A,random_tensor_B.T)
print(output)
output.shape '''

tensor([[0.9124, 0.5624, 0.9478, 0.8059, 0.1839, 0.7243, 0.1466]])
tensor([[0.2881],
        [0.6471],
        [0.6651],
        [0.8751],
        [0.3390],
        [0.5008],
        [0.7574]])
tensor([[2.4985]])


torch.Size([1, 1])

In [ ]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(f"Oringinal shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A ={tensor_A.shape} (same as above),tensor_B.T ={tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape}*{tensor_B.T.shape}<-inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Oringinal shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A =torch.Size([3, 2]) (same as above),tensor_B.T =torch.Size([2, 3])

Multiplying: torch.Size([3, 2])*torch.Size([2, 3])<-inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape:torch.Size([3, 3])


In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\n Output shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

 Output shape: torch.Size([3, 6])


In [ ]:
'''#Exercise 4
torch.manual_seed(0)
linear = torch.nn.Linear(in_features = 7, out_features = 7)
x=random_tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")'''



Input shape: torch.Size([1, 7])

Output:
tensor([[-0.3757,  0.1872,  0.4196,  0.8155, -0.3061,  0.2699, -0.5988]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([1, 7])


In [ ]:
 x =torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimun: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimun: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
tensor =torch.arange(10,100,10)
print(f"Tensor:{tensor}")
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
tensor =torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z=x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:, 0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape :{x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape :torch.Size([1, 7])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7.])
New shape : torch.Size([7])


In [ ]:
print(f"Previous tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor :{x_unsqueezed}")
print (f"New shape: {x_unsqueezed.shape}")

Previous tensor : tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape : torch.Size([7])

New tensor :tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
x_original = torch.rand(size=(224,224,3))

x_permuted= x_original.permute(2,0,1)
print(f"Previous shape:{x_original.shape}")
print(f"new shape: {x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"First squre bracket :\n{x[0]}")
print(f"Second squre bracket: {x[0][0]}")
print(f"Third squre bracket: {x[0][0][0]}")

First squre bracket :
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second squre bracket: tensor([1, 2, 3])
Third squre bracket: 1


In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor +1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"Tensor A:\n{random_tensor_A}")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B?(anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.3956, 0.7390, 0.3317, 0.5313],
        [0.1853, 0.5148, 0.1994, 0.3444],
        [0.9941, 0.8115, 0.1249, 0.0330]])
Tensor B:
tensor([[0.9084, 0.3886, 0.8393, 0.9454],
        [0.1458, 0.7199, 0.6507, 0.1943],
        [0.2501, 0.3986, 0.9127, 0.5200]])

Does Tensor A equal Tensor B?(anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random
RANDOM_SEED= 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D?(anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D?(anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
device ="cuda" if torch.cuda.is_available() else "cup"
device

'cup'

In [ ]:
torch.cuda.device_count()

0

In [ ]:
import torch
torch.backends.mps.is_available()#mac user only

False

In [ ]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [ ]:
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])